#!/bin/bash

HYSTERESIS=6000   # in mK
SLEEP_INTERVAL=1  # in s
DEBUG=true

# set temps (in degrees C * 1000) and corresponding pwm values in ascending order and with the same amount of values
TEMPS=( 65000 80000 90000 )
PWMS=(      0   153   255 )

cards=$(echo $1|tr ',' ' ')

if [ "$cards" == "" ]; then 
	cards = "0";
fi

# hwmon paths, hardcoded for one amdgpu card, adjust as needed
FILE_PWM=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/pwm1)
FILE_FANMODE=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/pwm1_enable)
FILE_TEMP=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/temp1_input)
# might want to use this later
#FILE_TEMP_CRIT=$(echo /sys/class/hwmon/hwmon?/temp1_crit_hyst)

# load configuration file if present
[ -f /etc/amdgpu-fancontrol.cfg ] && . /etc/amdgpu-fancontrol.cfg


# check if amount of temps and pwm values match
if [ "${#TEMPS[@]}" -ne "${#PWMS[@]}" ]
then
  echo "Amount of temperature and pwm values does not match"
  exit 1
fi

# checking for privileges
if [ $UID -ne 0 ]
then
  echo "Writing to sysfs requires privileges, relaunch as root"
  exit 1
fi

function debug {
  if $DEBUG; then
    echo $1
  fi
}

# set fan mode to max(0), manual(1) or auto(2)
function set_fanmode {
  card=$2
  FILE_FANMODE=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/pwm1_enable)
  echo "setting fan mode for $card to $1"
  echo "$1" > "$FILE_FANMODE"
}

function set_pwm {
  NEW_PWM=$1
  card=$2
  FILE_PWM=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/pwm1)
  FILE_FANMODE=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/pwm1_enable)
  FILE_TEMP=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/temp1_input)

  OLD_PWM=$(cat $FILE_PWM)

  debug "current pwm: $OLD_PWM, requested to set pwm to $NEW_PWM"
  if [ $(cat ${FILE_FANMODE}) -ne 1 ]
  then
    echo "Fanmode not set to manual."
    set_fanmode 1 $card
  fi

  if [ -z "${TEMP_AT_LAST_PWM_CHANGE[card]}" ] || [ "$TEMP" -gt "${TEMP_AT_LAST_PWM_CHANGE[card]}" ] || [ $(($(cat $FILE_TEMP) + HYSTERESIS)) -le "${TEMP_AT_LAST_PWM_CHANGE[card]}" ]; then
    $DEBUG || echo "card $card: current temp: $TEMP"
    echo "card $card: temp at last change was ${TEMP_AT_LAST_PWM_CHANGE[card]}"
    echo "card $card: changing pwm to $NEW_PWM"
    echo "$NEW_PWM" > "$FILE_PWM"
    TEMP_AT_LAST_PWM_CHANGE[card]=$(cat $FILE_TEMP)
  else
    debug "card $card: not changing pwm, we just did at ${TEMP_AT_LAST_PWM_CHANGE[card]}, next change when below $((TEMP_AT_LAST_PWM_CHANGE[card] - HYSTERESIS))"
  fi
}

function interpolate_pwm {
  i=0
  card=$1
  FILE_TEMP=$(echo /sys/class/drm/card$card/device/hwmon/hwmon?/temp1_input)
  TEMP=$(cat $FILE_TEMP)

  debug "card $card: current temp: $TEMP"

  if [[ $TEMP -le ${TEMPS[0]} ]]; then
    # below first point in list, set to min speed
    set_pwm "${PWMS[i]}" $card
    return
  elif [[ $TEMP -gt ${TEMPS[-1]} ]]; then
    # above last point in list, set to max speed
    set_pwm "${PWMS[-1]}" $card
    return
  fi

  for i in "${!TEMPS[@]}"; do
    if [[ $TEMP -gt ${TEMPS[$i]} ]]; then
      continue
    fi

    # interpolate linearly
    LOWERTEMP=${TEMPS[i-1]}
    HIGHERTEMP=${TEMPS[i]}
    LOWERPWM=${PWMS[i-1]}
    HIGHERPWM=${PWMS[i]}
    PWM=$(echo "( ( $TEMP - $LOWERTEMP ) * ( $HIGHERPWM - $LOWERPWM ) / ( $HIGHERTEMP - $LOWERTEMP ) ) + $LOWERPWM" | bc)
    debug "card $card: interpolated pwm value for temperature $TEMP is: $PWM"
    set_pwm "$PWM" $card
    return
  done
}

function reset_on_exit {
  echo "exiting, resetting fan to auto control..."
  for c in $cards ; do 
    set_fanmode 2 $c
  done
  exit 0
}

# always try to reset fans on exit
trap "reset_on_exit" SIGINT SIGTERM

function run_daemon {
  while :; do
    for card in $cards; do   
    	interpolate_pwm $card
    	debug
    done
    sleep $SLEEP_INTERVAL
  done
}

# set fan control to manual
for card in $cards ; do
  set_fanmode 1 $card
done

# finally start the loop
run_daemon

